// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <string>
#include <utility>

namespace ProtonMail {

struct EncryptSignPackage final {
    std::string encrypted;
    std::string signature;

    EncryptSignPackage(std::string encrypted_,
                       std::string signature_)
    : encrypted(std::move(encrypted_))
    , signature(std::move(signature_))
    {}
};

}  // namespace ProtonMail
