// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace ProtonMail {

struct EncryptPackage final {
    std::vector<uint8_t> key_package;
    std::vector<uint8_t> data_package;

    EncryptPackage(std::vector<uint8_t> key_package_,
                   std::vector<uint8_t> data_package_)
    : key_package(std::move(key_package_))
    , data_package(std::move(data_package_))
    {}
};

}  // namespace ProtonMail
