// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>

namespace ProtonMail {

class OpenPgpKeyManager {
public:
    virtual ~OpenPgpKeyManager() {}

    static std::shared_ptr<OpenPgpKeyManager> create_instance();
};

}  // namespace ProtonMail
