// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace ProtonMail {

struct SrpProofs final {
    std::vector<uint8_t> client_ephemeral;
    std::vector<uint8_t> client_proof;
    std::vector<uint8_t> expected_server_proof;

    SrpProofs(std::vector<uint8_t> client_ephemeral_,
              std::vector<uint8_t> client_proof_,
              std::vector<uint8_t> expected_server_proof_)
    : client_ephemeral(std::move(client_ephemeral_))
    , client_proof(std::move(client_proof_))
    , expected_server_proof(std::move(expected_server_proof_))
    {}
};

}  // namespace ProtonMail
