//
//  chaining_writer.cpp
//  OpenPGP
//
//  Created by Yanfeng Zhang on 5/8/17.
//  Copyright © 2017 Yanfeng Zhang. All rights reserved.
//

#include "chaining_writer.hpp"

namespace ezvcard {
    

/**
 * @param vcards the vCards to write
 */
ChainingWriter::ChainingWriter(std::vector<VCard::Ptr> vcards) {
    _vcards = vcards;
}


/**
 * Sets whether to exclude properties that do not support the target version
 * from the written vCard.
 * @param versionStrict true to exclude such properties, false not to
 * (defaults to true)
 * @return this
 */
void ChainingWriter::versionStrict(bool versionStrict) {
    _versionStrict = versionStrict;
}

/**
 * Sets whether to add a {@link ProductId} property to each vCard that marks
 * it as having been generated by this library. For 2.1 vCards, the extended
 * property "X-PRODID" will be added, since {@link ProductId} is not
 * supported by that version.
 * @param include true to add the property, false not to (defaults to true)
 * @return this
 */
void ChainingWriter::prodId(bool include) {
    _prodId = include;
}

/**
 * Registers a property scribe.
 * @param scribe the scribe to register
 * @return this
 */
//void register(VCardPropertyScribe<? extends VCardProperty> scribe) {
//    if (index == null) {
//        index = new ScribeIndex();
//    }
//    index.register(scribe);
//    return this_;
//}

    
}
