// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils;

import java.util.ArrayList;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public final class Address {


    /*package*/ final String mAddressId;

    /*package*/ final String mAddressName;

    /*package*/ final ArrayList<String> mKeys;

    public Address(
            @Nonnull String addressId,
            @Nonnull String addressName,
            @Nonnull ArrayList<String> keys) {
        this.mAddressId = addressId;
        this.mAddressName = addressName;
        this.mKeys = keys;
    }

    @Nonnull
    public String getAddressId() {
        return mAddressId;
    }

    /**optional */
    @Nonnull
    public String getAddressName() {
        return mAddressName;
    }

    @Nonnull
    public ArrayList<String> getKeys() {
        return mKeys;
    }

    @Override
    public String toString() {
        return "Address{" +
                "mAddressId=" + mAddressId +
                "," + "mAddressName=" + mAddressName +
                "," + "mKeys=" + mKeys +
        "}";
    }

}
