// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils;

public final class EncryptPackage {


    /*package*/ final byte[] keyPackage;

    /*package*/ final byte[] dataPackage;

    public EncryptPackage(
            byte[] keyPackage,
            byte[] dataPackage) {
        this.keyPackage = keyPackage;
        this.dataPackage = dataPackage;
    }

    public byte[] getKeyPackage() {
        return keyPackage;
    }

    public byte[] getDataPackage() {
        return dataPackage;
    }

    @Override
    public String toString() {
        return "EncryptPackage{" +
                "keyPackage=" + keyPackage +
                "," + "dataPackage=" + dataPackage +
        "}";
    }

}
