// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public final class SrpProofs {


    /*package*/ final byte[] mClientEphemeral;

    /*package*/ final byte[] mClientProof;

    /*package*/ final byte[] mExpectedServerProof;

    public SrpProofs(
            @Nonnull byte[] clientEphemeral,
            @Nonnull byte[] clientProof,
            @Nonnull byte[] expectedServerProof) {
        this.mClientEphemeral = clientEphemeral;
        this.mClientProof = clientProof;
        this.mExpectedServerProof = expectedServerProof;
    }

    @Nonnull
    public byte[] getClientEphemeral() {
        return mClientEphemeral;
    }

    @Nonnull
    public byte[] getClientProof() {
        return mClientProof;
    }

    @Nonnull
    public byte[] getExpectedServerProof() {
        return mExpectedServerProof;
    }

    @Override
    public String toString() {
        return "SrpProofs{" +
                "mClientEphemeral=" + mClientEphemeral +
                "," + "mClientProof=" + mClientProof +
                "," + "mExpectedServerProof=" + mExpectedServerProof +
        "}";
    }

}
