// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNAddress.h"


@implementation PMNAddress

- (nonnull instancetype)initWithAddressId:(nonnull NSString *)addressId
                              addressName:(nonnull NSString *)addressName
                                     keys:(nonnull NSArray<PMNOpenPgpKey *> *)keys
{
    if (self = [super init]) {
        _addressId = [addressId copy];
        _addressName = [addressName copy];
        _keys = [keys copy];
    }
    return self;
}

+ (nonnull instancetype)addressWithAddressId:(nonnull NSString *)addressId
                                 addressName:(nonnull NSString *)addressName
                                        keys:(nonnull NSArray<PMNOpenPgpKey *> *)keys
{
    return [[self alloc] initWithAddressId:addressId
                               addressName:addressName
                                      keys:keys];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p addressId:%@ addressName:%@ keys:%@>", self.class, self, self.addressId, self.addressName, self.keys];
}

@end
