// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNEncryptPackage.h"


@implementation PMNEncryptPackage

- (nonnull instancetype)initWithKeyPackage:(nonnull NSData *)keyPackage
                               dataPackage:(nonnull NSData *)dataPackage
{
    if (self = [super init]) {
        _keyPackage = [keyPackage copy];
        _dataPackage = [dataPackage copy];
    }
    return self;
}

+ (nonnull instancetype)encryptPackageWithKeyPackage:(nonnull NSData *)keyPackage
                                         dataPackage:(nonnull NSData *)dataPackage
{
    return [[self alloc] initWithKeyPackage:keyPackage
                                dataPackage:dataPackage];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p keyPackage:%@ dataPackage:%@>", self.class, (void *)self, self.keyPackage, self.dataPackage];
}

@end
