// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNEncryptPackage.h"
#include "bridge/encrypt_package.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNEncryptPackage;

namespace OBJ_ProtonMail {

struct EncryptPackage
{
    using CppType = ::ProtonMail::EncryptPackage;
    using ObjcType = PMNEncryptPackage*;

    using Boxed = EncryptPackage;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace OBJ_ProtonMail
