// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNOpenPgpKey.h"


@implementation PMNOpenPgpKey

- (nonnull instancetype)initWithPublicKey:(nonnull NSString *)publicKey
                               privateKey:(nonnull NSString *)privateKey
{
    if (self = [super init]) {
        _publicKey = [publicKey copy];
        _privateKey = [privateKey copy];
    }
    return self;
}

+ (nonnull instancetype)openPgpKeyWithPublicKey:(nonnull NSString *)publicKey
                                     privateKey:(nonnull NSString *)privateKey
{
    return [[self alloc] initWithPublicKey:publicKey
                                privateKey:privateKey];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p publicKey:%@ privateKey:%@>", self.class, self, self.publicKey, self.privateKey];
}

@end
