// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNOpenPgpKeyManager+Private.h"
#import "PMNOpenPgpKeyManager.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNOpenPgpKeyManager ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::OpenPgpKeyManager>&)cppRef;

@end

@implementation PMNOpenPgpKeyManager {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::OpenPgpKeyManager>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::OpenPgpKeyManager>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable PMNOpenPgpKeyManager *)createInstance {
    try {
        auto objcpp_result_ = ::ProtonMail::OpenPgpKeyManager::create_instance();
        return ::OBJ_ProtonMail::OpenPgpKeyManager::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto OpenPgpKeyManager::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto OpenPgpKeyManager::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNOpenPgpKeyManager>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
