// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNSrpProofs+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace OBJ_ProtonMail {

auto SrpProofs::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Binary::toCpp(obj.clientEphemeral),
            ::djinni::Binary::toCpp(obj.clientProof),
            ::djinni::Binary::toCpp(obj.expectedServerProof)};
}

auto SrpProofs::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[PMNSrpProofs alloc] initWithClientEphemeral:(::djinni::Binary::fromCpp(cpp.client_ephemeral))
                                             clientProof:(::djinni::Binary::fromCpp(cpp.client_proof))
                                     expectedServerProof:(::djinni::Binary::fromCpp(cpp.expected_server_proof))];
}

}  // namespace OBJ_ProtonMail
