// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "bridge/srp_client.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNSrpClient;

namespace OBJ_ProtonMail {

class SrpClient
{
public:
    using CppType = std::shared_ptr<::ProtonMail::SrpClient>;
    using CppOptType = std::shared_ptr<::ProtonMail::SrpClient>;
    using ObjcType = PMNSrpClient*;

    using Boxed = SrpClient;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace OBJ_ProtonMail

