// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNSrpClient+Private.h"
#import "PMNSrpClient.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "PMNSrpProofs+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNSrpClient ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::SrpClient>&)cppRef;

@end

@implementation PMNSrpClient {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::SrpClient>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::SrpClient>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSData *)expandHash:(nonnull NSData *)input {
    try {
        auto objcpp_result_ = ::ProtonMail::SrpClient::expand_hash(::djinni::Binary::toCpp(input));
        return ::djinni::Binary::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull PMNSrpProofs *)generateProofs:(int32_t)bitLength
                             modulusRepr:(nonnull NSData *)modulusRepr
                     serverEphemeralRepr:(nonnull NSData *)serverEphemeralRepr
                      hashedPasswordRepr:(nonnull NSData *)hashedPasswordRepr {
    try {
        auto objcpp_result_ = ::ProtonMail::SrpClient::generate_proofs(::djinni::I32::toCpp(bitLength),
                                                                       ::djinni::Binary::toCpp(modulusRepr),
                                                                       ::djinni::Binary::toCpp(serverEphemeralRepr),
                                                                       ::djinni::Binary::toCpp(hashedPasswordRepr));
        return ::OBJ_ProtonMail::SrpProofs::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSData *)generateVerifier:(int32_t)bitLength
                         modulusRepr:(nonnull NSData *)modulusRepr
                  hashedPasswordRepr:(nonnull NSData *)hashedPasswordRepr {
    try {
        auto objcpp_result_ = ::ProtonMail::SrpClient::generate_Verifier(::djinni::I32::toCpp(bitLength),
                                                                         ::djinni::Binary::toCpp(modulusRepr),
                                                                         ::djinni::Binary::toCpp(hashedPasswordRepr));
        return ::djinni::Binary::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto SrpClient::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SrpClient::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNSrpClient>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
