// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNAddress.h"
#include "bridge/address.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNAddress;

namespace OBJ_ProtonMail {

struct Address
{
    using CppType = ::ProtonMail::Address;
    using ObjcType = PMNAddress*;

    using Boxed = Address;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace OBJ_ProtonMail
