// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "bridge/b_crypt_hash.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNBCryptHash;

namespace OBJ_ProtonMail {

class BCryptHash
{
public:
    using CppType = std::shared_ptr<::ProtonMail::BCryptHash>;
    using CppOptType = std::shared_ptr<::ProtonMail::BCryptHash>;
    using ObjcType = PMNBCryptHash*;

    using Boxed = BCryptHash;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace OBJ_ProtonMail

