// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNDecryptSignVerify.h"
#include "bridge/decrypt_sign_verify.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNDecryptSignVerify;

namespace OBJ_ProtonMail {

struct DecryptSignVerify
{
    using CppType = ::ProtonMail::DecryptSignVerify;
    using ObjcType = PMNDecryptSignVerify*;

    using Boxed = DecryptSignVerify;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace OBJ_ProtonMail
