// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNITelephone+Private.h"
#import "PMNITelephone.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNITelephone ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::ITelephone>&)cppRef;

@end

@implementation PMNITelephone {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::ITelephone>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::ITelephone>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSArray<NSString *> *)getTypes {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getTypes();
        return ::djinni::List<::djinni::String>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getText {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getText();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNITelephone *)createInstance:(nonnull NSString *)type
                                    number:(nonnull NSString *)number {
    try {
        auto objcpp_result_ = ::ProtonMail::ITelephone::create_instance(::djinni::String::toCpp(type),
                                                                        ::djinni::String::toCpp(number));
        return ::OBJ_ProtonMail::ITelephone::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto ITelephone::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ITelephone::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNITelephone>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
