// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNITitle+Private.h"
#import "PMNITitle.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNITitle ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::ITitle>&)cppRef;

@end

@implementation PMNITitle {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::ITitle>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::ITitle>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getTitle {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getTitle();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getType {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getType();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNITitle *)createInstance:(nonnull NSString *)type
                                 value:(nonnull NSString *)value {
    try {
        auto objcpp_result_ = ::ProtonMail::ITitle::create_instance(::djinni::String::toCpp(type),
                                                                    ::djinni::String::toCpp(value));
        return ::OBJ_ProtonMail::ITitle::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto ITitle::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ITitle::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNITitle>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
