// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNINote+Private.h"
#import "PMNINote.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNINote ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::INote>&)cppRef;

@end

@implementation PMNINote {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::INote>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::INote>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getType {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getType();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getNote {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getNote();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNINote *)createInstance:(nonnull NSString *)type
                                 note:(nonnull NSString *)note {
    try {
        auto objcpp_result_ = ::ProtonMail::INote::create_instance(::djinni::String::toCpp(type),
                                                                   ::djinni::String::toCpp(note));
        return ::OBJ_ProtonMail::INote::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto INote::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto INote::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNINote>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
