// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIAnniversary+Private.h"
#import "PMNIAnniversary.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIAnniversary ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IAnniversary>&)cppRef;

@end

@implementation PMNIAnniversary {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IAnniversary>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IAnniversary>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getDate {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getDate();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getType {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getType();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIAnniversary *)createInstance:(nonnull NSString *)type
                                        date:(nonnull NSString *)date {
    try {
        auto objcpp_result_ = ::ProtonMail::IAnniversary::create_instance(::djinni::String::toCpp(type),
                                                                          ::djinni::String::toCpp(date));
        return ::OBJ_ProtonMail::IAnniversary::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto IAnniversary::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IAnniversary::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIAnniversary>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
