// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIEmail+Private.h"
#import "PMNIEmail.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIEmail ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IEmail>&)cppRef;

@end

@implementation PMNIEmail {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IEmail>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IEmail>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getParameter:(nonnull NSString *)name {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getParameter(::djinni::String::toCpp(name));
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getValue {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getValue();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<NSString *> *)getTypes {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getTypes();
        return ::djinni::List<::djinni::String>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getGroup {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getGroup();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setGroup:(nonnull NSString *)g {
    try {
        _cppRefHandle.get()->setGroup(::djinni::String::toCpp(g));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIEmail *)createInstance:(nonnull NSString *)type
                                 email:(nonnull NSString *)email
                                 group:(nonnull NSString *)group {
    try {
        auto objcpp_result_ = ::ProtonMail::IEmail::create_instance(::djinni::String::toCpp(type),
                                                                    ::djinni::String::toCpp(email),
                                                                    ::djinni::String::toCpp(group));
        return ::OBJ_ProtonMail::IEmail::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto IEmail::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IEmail::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIEmail>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
