// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "bridge/i_p_m_mime_type.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNIPMMimeType;

namespace OBJ_ProtonMail {

class IPMMimeType
{
public:
    using CppType = std::shared_ptr<::ProtonMail::IPMMimeType>;
    using CppOptType = std::shared_ptr<::ProtonMail::IPMMimeType>;
    using ObjcType = PMNIPMMimeType*;

    using Boxed = IPMMimeType;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace OBJ_ProtonMail

