// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "bridge/i_categories.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNICategories;

namespace OBJ_ProtonMail {

class ICategories
{
public:
    using CppType = std::shared_ptr<::ProtonMail::ICategories>;
    using CppOptType = std::shared_ptr<::ProtonMail::ICategories>;
    using ObjcType = PMNICategories*;

    using Boxed = ICategories;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace OBJ_ProtonMail

