// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNICategories+Private.h"
#import "PMNICategories.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNICategories ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::ICategories>&)cppRef;

@end

@implementation PMNICategories {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::ICategories>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::ICategories>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSArray<NSString *> *)getValues {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getValues();
        return ::djinni::List<::djinni::String>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)addValue:(nonnull NSString *)text {
    try {
        _cppRefHandle.get()->addValue(::djinni::String::toCpp(text));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setValues:(nonnull NSArray<NSString *> *)values {
    try {
        _cppRefHandle.get()->setValues(::djinni::List<::djinni::String>::toCpp(values));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getGroup {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getGroup();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setGroup:(nonnull NSString *)g {
    try {
        _cppRefHandle.get()->setGroup(::djinni::String::toCpp(g));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNICategories *)createInstance:(nonnull NSString *)group
                                      value:(nonnull NSArray<NSString *> *)value {
    try {
        auto objcpp_result_ = ::ProtonMail::ICategories::create_instance(::djinni::String::toCpp(group),
                                                                         ::djinni::List<::djinni::String>::toCpp(value));
        return ::OBJ_ProtonMail::ICategories::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto ICategories::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ICategories::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNICategories>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
