// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "bridge/i_organization.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNIOrganization;

namespace OBJ_ProtonMail {

class IOrganization
{
public:
    using CppType = std::shared_ptr<::ProtonMail::IOrganization>;
    using CppOptType = std::shared_ptr<::ProtonMail::IOrganization>;
    using ObjcType = PMNIOrganization*;

    using Boxed = IOrganization;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace OBJ_ProtonMail

