// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "bridge/i_key.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNIKey;

namespace OBJ_ProtonMail {

class IKey
{
public:
    using CppType = std::shared_ptr<::ProtonMail::IKey>;
    using CppOptType = std::shared_ptr<::ProtonMail::IKey>;
    using ObjcType = PMNIKey*;

    using Boxed = IKey;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace OBJ_ProtonMail

