// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIPMSign+Private.h"
#import "PMNIPMSign.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIPMSign ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IPMSign>&)cppRef;

@end

@implementation PMNIPMSign {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IPMSign>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IPMSign>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getValue {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getValue();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getType {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getType();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getGroup {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getGroup();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIPMSign *)createInstance:(nonnull NSString *)type
                                  value:(nonnull NSString *)value {
    try {
        auto objcpp_result_ = ::ProtonMail::IPMSign::create_instance(::djinni::String::toCpp(type),
                                                                     ::djinni::String::toCpp(value));
        return ::OBJ_ProtonMail::IPMSign::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto IPMSign::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IPMSign::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIPMSign>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
