// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIOrganization+Private.h"
#import "PMNIOrganization.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIOrganization ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IOrganization>&)cppRef;

@end

@implementation PMNIOrganization {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IOrganization>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IOrganization>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSArray<NSString *> *)getValues {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getValues();
        return ::djinni::List<::djinni::String>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getValue {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getValue();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIOrganization *)createInstance:(nonnull NSString *)type
                                        value:(nonnull NSString *)value {
    try {
        auto objcpp_result_ = ::ProtonMail::IOrganization::create_instance(::djinni::String::toCpp(type),
                                                                           ::djinni::String::toCpp(value));
        return ::OBJ_ProtonMail::IOrganization::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto IOrganization::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IOrganization::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIOrganization>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
