// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIPMEncrypt+Private.h"
#import "PMNIPMEncrypt.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIPMEncrypt ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IPMEncrypt>&)cppRef;

@end

@implementation PMNIPMEncrypt {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IPMEncrypt>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IPMEncrypt>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)getValue {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getValue();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getType {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getType();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getGroup {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getGroup();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIPMEncrypt *)createInstance:(nonnull NSString *)type
                                     value:(nonnull NSString *)value {
    try {
        auto objcpp_result_ = ::ProtonMail::IPMEncrypt::create_instance(::djinni::String::toCpp(type),
                                                                        ::djinni::String::toCpp(value));
        return ::OBJ_ProtonMail::IPMEncrypt::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto IPMEncrypt::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IPMEncrypt::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIPMEncrypt>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
