// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "bridge/i_uid.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNIUid;

namespace OBJ_ProtonMail {

class IUid
{
public:
    using CppType = std::shared_ptr<::ProtonMail::IUid>;
    using CppOptType = std::shared_ptr<::ProtonMail::IUid>;
    using ObjcType = PMNIUid*;

    using Boxed = IUid;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace OBJ_ProtonMail

