// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIPhoto+Private.h"
#import "PMNIPhoto.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIPhoto ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IPhoto>&)cppRef;

@end

@implementation PMNIPhoto {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IPhoto>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IPhoto>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

namespace OBJ_ProtonMail {

auto IPhoto::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IPhoto::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIPhoto>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
