// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIEzvcard+Private.h"
#import "PMNIEzvcard.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "PMNIVCard+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIEzvcard ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IEzvcard>&)cppRef;

@end

@implementation PMNIEzvcard {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IEzvcard>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IEzvcard>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable PMNIVCard *)parseFirst:(nonnull NSString *)value {
    try {
        auto objcpp_result_ = ::ProtonMail::IEzvcard::parse_first(::djinni::String::toCpp(value));
        return ::OBJ_ProtonMail::IVCard::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSArray<PMNIVCard *> *)parseAll:(nonnull NSString *)value {
    try {
        auto objcpp_result_ = ::ProtonMail::IEzvcard::parse_all(::djinni::String::toCpp(value));
        return ::djinni::List<::OBJ_ProtonMail::IVCard>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSString *)write:(nullable PMNIVCard *)vcard {
    try {
        auto objcpp_result_ = ::ProtonMail::IEzvcard::write(::OBJ_ProtonMail::IVCard::toCpp(vcard));
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSString *)writeAll:(nonnull NSArray<PMNIVCard *> *)vcards {
    try {
        auto objcpp_result_ = ::ProtonMail::IEzvcard::write_all(::djinni::List<::OBJ_ProtonMail::IVCard>::toCpp(vcards));
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto IEzvcard::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IEzvcard::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIEzvcard>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
