// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNIVCardVersion+Private.h"
#import "PMNIVCardVersion.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface PMNIVCardVersion ()

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IVCardVersion>&)cppRef;

@end

@implementation PMNIVCardVersion {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ProtonMail::IVCardVersion>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ProtonMail::IVCardVersion>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (BOOL)equals:(nullable PMNIVCardVersion *)rhs {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->equals(::OBJ_ProtonMail::IVCardVersion::toCpp(rhs));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIVCardVersion *)VCard21 {
    try {
        auto objcpp_result_ = ::ProtonMail::IVCardVersion::VCard2_1();
        return ::OBJ_ProtonMail::IVCardVersion::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIVCardVersion *)VCard30 {
    try {
        auto objcpp_result_ = ::ProtonMail::IVCardVersion::VCard3_0();
        return ::OBJ_ProtonMail::IVCardVersion::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable PMNIVCardVersion *)VCard40 {
    try {
        auto objcpp_result_ = ::ProtonMail::IVCardVersion::VCard4_0();
        return ::OBJ_ProtonMail::IVCardVersion::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace OBJ_ProtonMail {

auto IVCardVersion::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IVCardVersion::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<PMNIVCardVersion>(cpp);
}

}  // namespace OBJ_ProtonMail

@end
