// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNOpenPgpKey+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace OBJ_ProtonMail {

auto OpenPgpKey::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.publicKey),
            ::djinni::String::toCpp(obj.privateKey)};
}

auto OpenPgpKey::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[PMNOpenPgpKey alloc] initWithPublicKey:(::djinni::String::fromCpp(cpp.public_key))
                                         privateKey:(::djinni::String::fromCpp(cpp.private_key))];
}

}  // namespace OBJ_ProtonMail
