// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNOpenPgpKey.h"
#include "bridge/open_pgp_key.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNOpenPgpKey;

namespace OBJ_ProtonMail {

struct OpenPgpKey
{
    using CppType = ::ProtonMail::OpenPgpKey;
    using ObjcType = PMNOpenPgpKey*;

    using Boxed = OpenPgpKey;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace OBJ_ProtonMail
