// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#import "PMNSrpProofs.h"
#include "bridge/srp_proofs.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PMNSrpProofs;

namespace OBJ_ProtonMail {

struct SrpProofs
{
    using CppType = ::ProtonMail::SrpProofs;
    using ObjcType = PMNSrpProofs*;

    using Boxed = SrpProofs;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace OBJ_ProtonMail
