// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeSrpClient.hpp"  // my header
#include "NativeSrpProofs.hpp"
#include "jni_base_h/Marshal.hpp"

namespace ProtonMail {

NativeSrpClient::NativeSrpClient() : ::djinni::JniInterface<::ProtonMail::SrpClient, NativeSrpClient>("ch/protonmail/android/utils/nativelib/SrpClient$CppProxy") {}

NativeSrpClient::~NativeSrpClient() = default;


CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_SrpClient_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ProtonMail::SrpClient>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jbyteArray JNICALL Java_ch_protonmail_android_utils_nativelib_SrpClient_expandHash(JNIEnv* jniEnv, jobject /*this*/, jbyteArray j_input)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::SrpClient::expand_hash(::djinni::Binary::toCpp(jniEnv, j_input));
        return ::djinni::release(::djinni::Binary::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_SrpClient_generateProofs(JNIEnv* jniEnv, jobject /*this*/, jint j_bitLength, jbyteArray j_modulusRepr, jbyteArray j_serverEphemeralRepr, jbyteArray j_hashedPasswordRepr)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::SrpClient::generate_proofs(::djinni::I32::toCpp(jniEnv, j_bitLength),
                                                          ::djinni::Binary::toCpp(jniEnv, j_modulusRepr),
                                                          ::djinni::Binary::toCpp(jniEnv, j_serverEphemeralRepr),
                                                          ::djinni::Binary::toCpp(jniEnv, j_hashedPasswordRepr));
        return ::djinni::release(::ProtonMail::NativeSrpProofs::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jbyteArray JNICALL Java_ch_protonmail_android_utils_nativelib_SrpClient_generateVerifier(JNIEnv* jniEnv, jobject /*this*/, jint j_bitLength, jbyteArray j_modulusRepr, jbyteArray j_hashedPasswordRepr)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::SrpClient::generate_Verifier(::djinni::I32::toCpp(jniEnv, j_bitLength),
                                                            ::djinni::Binary::toCpp(jniEnv, j_modulusRepr),
                                                            ::djinni::Binary::toCpp(jniEnv, j_hashedPasswordRepr));
        return ::djinni::release(::djinni::Binary::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace ProtonMail
