// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeIVCardVersion.hpp"  // my header
#include "jni_base_h/Marshal.hpp"

namespace ProtonMail {

NativeIVCardVersion::NativeIVCardVersion() : ::djinni::JniInterface<::ProtonMail::IVCardVersion, NativeIVCardVersion>("ch/protonmail/android/utils/nativelib/IVCardVersion$CppProxy") {}

NativeIVCardVersion::~NativeIVCardVersion() = default;


CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCardVersion_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ProtonMail::IVCardVersion>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_ch_protonmail_android_utils_nativelib_IVCardVersion_00024CppProxy_native_1equals(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_rhs)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCardVersion>(nativeRef);
        auto r = ref->equals(::ProtonMail::NativeIVCardVersion::toCpp(jniEnv, j_rhs));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCardVersion_00024CppProxy_VCard21(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::IVCardVersion::VCard2_1();
        return ::djinni::release(::ProtonMail::NativeIVCardVersion::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCardVersion_00024CppProxy_VCard30(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::IVCardVersion::VCard3_0();
        return ::djinni::release(::ProtonMail::NativeIVCardVersion::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCardVersion_00024CppProxy_VCard40(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::IVCardVersion::VCard4_0();
        return ::djinni::release(::ProtonMail::NativeIVCardVersion::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace ProtonMail
