// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeSrpProofs.hpp"  // my header
#include "jni_base_h/Marshal.hpp"

namespace ProtonMail {

NativeSrpProofs::NativeSrpProofs() = default;

NativeSrpProofs::~NativeSrpProofs() = default;

auto NativeSrpProofs::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSrpProofs>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Binary::fromCpp(jniEnv, c.client_ephemeral)),
                                                           ::djinni::get(::djinni::Binary::fromCpp(jniEnv, c.client_proof)),
                                                           ::djinni::get(::djinni::Binary::fromCpp(jniEnv, c.expected_server_proof)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSrpProofs::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSrpProofs>::get();
    return {::djinni::Binary::toCpp(jniEnv, (jbyteArray)jniEnv->GetObjectField(j, data.field_mClientEphemeral)),
            ::djinni::Binary::toCpp(jniEnv, (jbyteArray)jniEnv->GetObjectField(j, data.field_mClientProof)),
            ::djinni::Binary::toCpp(jniEnv, (jbyteArray)jniEnv->GetObjectField(j, data.field_mExpectedServerProof))};
}

}  // namespace ProtonMail
