// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeIVCard.hpp"  // my header
#include "NativeIAddress.hpp"
#include "NativeIBirthday.hpp"
#include "NativeICategories.hpp"
#include "NativeIEmail.hpp"
#include "NativeIFormattedName.hpp"
#include "NativeIGender.hpp"
#include "NativeIKey.hpp"
#include "NativeINickname.hpp"
#include "NativeINote.hpp"
#include "NativeIOrganization.hpp"
#include "NativeIPMCustom.hpp"
#include "NativeIPMEncrypt.hpp"
#include "NativeIPMMimeType.hpp"
#include "NativeIPMScheme.hpp"
#include "NativeIPMSign.hpp"
#include "NativeIPhoto.hpp"
#include "NativeIStructuredName.hpp"
#include "NativeITelephone.hpp"
#include "NativeITitle.hpp"
#include "NativeIUid.hpp"
#include "NativeIUrl.hpp"
#include "NativeIVCardVersion.hpp"
#include "jni_base_h/Marshal.hpp"

namespace ProtonMail {

NativeIVCard::NativeIVCard() : ::djinni::JniInterface<::ProtonMail::IVCard, NativeIVCard>("ch/protonmail/android/utils/nativelib/IVCard$CppProxy") {}

NativeIVCard::~NativeIVCard() = default;


CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ProtonMail::IVCard>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getPropertyTypes(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getPropertyTypes();
        return ::djinni::release(::djinni::List<::djinni::String>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getVersion(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getVersion();
        return ::djinni::release(::ProtonMail::NativeIVCardVersion::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setVersion(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_version)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setVersion(::ProtonMail::NativeIVCardVersion::toCpp(jniEnv, j_version));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getFormattedName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getFormattedName();
        return ::djinni::release(::ProtonMail::NativeIFormattedName::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setFormattedName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_formattedName)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setFormattedName(::ProtonMail::NativeIFormattedName::toCpp(jniEnv, j_formattedName));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearFormattedName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearFormattedName();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getTelephoneNumbers(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getTelephoneNumbers();
        return ::djinni::release(::djinni::List<::ProtonMail::NativeITelephone>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addTelephone(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_cell)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addTelephone(::ProtonMail::NativeITelephone::toCpp(jniEnv, j_cell));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setTelephones(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_cells)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setTelephones(::djinni::List<::ProtonMail::NativeITelephone>::toCpp(jniEnv, j_cells));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearTelephones(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearTelephones();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getEmails(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getEmails();
        return ::djinni::release(::djinni::List<::ProtonMail::NativeIEmail>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addEmail(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_email)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addEmail(::ProtonMail::NativeIEmail::toCpp(jniEnv, j_email));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setEmails(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_emails)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setEmails(::djinni::List<::ProtonMail::NativeIEmail>::toCpp(jniEnv, j_emails));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearEmails(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearEmails();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getUid(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getUid();
        return ::djinni::release(::ProtonMail::NativeIUid::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setUid(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_uuid)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setUid(::ProtonMail::NativeIUid::toCpp(jniEnv, j_uuid));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getAddresses(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getAddresses();
        return ::djinni::release(::djinni::List<::ProtonMail::NativeIAddress>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addAddress(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_addr)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addAddress(::ProtonMail::NativeIAddress::toCpp(jniEnv, j_addr));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setAddresses(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_addrs)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setAddresses(::djinni::List<::ProtonMail::NativeIAddress>::toCpp(jniEnv, j_addrs));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearAddresses(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearAddresses();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getOrganization(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getOrganization();
        return ::djinni::release(::ProtonMail::NativeIOrganization::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addOrganization(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_org)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addOrganization(::ProtonMail::NativeIOrganization::toCpp(jniEnv, j_org));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setOrganizations(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_orgs)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setOrganizations(::djinni::List<::ProtonMail::NativeIOrganization>::toCpp(jniEnv, j_orgs));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearOrganizations(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearOrganizations();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getNote(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getNote();
        return ::djinni::release(::ProtonMail::NativeINote::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setNote(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_note)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setNote(::ProtonMail::NativeINote::toCpp(jniEnv, j_note));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearNote(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearNote();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getNickname(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getNickname();
        return ::djinni::release(::ProtonMail::NativeINickname::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setNickname(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_nickname)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setNickname(::ProtonMail::NativeINickname::toCpp(jniEnv, j_nickname));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearNickname(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearNickname();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getTitle(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getTitle();
        return ::djinni::release(::ProtonMail::NativeITitle::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setTitle(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_title)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setTitle(::ProtonMail::NativeITitle::toCpp(jniEnv, j_title));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearTitle(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearTitle();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getBirthdays(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getBirthdays();
        return ::djinni::release(::djinni::List<::ProtonMail::NativeIBirthday>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addBirthday(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_birthday)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addBirthday(::ProtonMail::NativeIBirthday::toCpp(jniEnv, j_birthday));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setBirthdays(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_birthdays)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setBirthdays(::djinni::List<::ProtonMail::NativeIBirthday>::toCpp(jniEnv, j_birthdays));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearBirthdays(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearBirthdays();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getCustoms(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getCustoms();
        return ::djinni::release(::djinni::List<::ProtonMail::NativeIPMCustom>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addCustom(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_custom)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addCustom(::ProtonMail::NativeIPMCustom::toCpp(jniEnv, j_custom));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setCustoms(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_customs)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setCustoms(::djinni::List<::ProtonMail::NativeIPMCustom>::toCpp(jniEnv, j_customs));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearCustoms(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearCustoms();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getPMSign(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getPMSign(::djinni::String::toCpp(jniEnv, j_group));
        return ::djinni::release(::ProtonMail::NativeIPMSign::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addPMSign(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_sign)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addPMSign(::ProtonMail::NativeIPMSign::toCpp(jniEnv, j_sign));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setPMSign(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_sign)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setPMSign(::ProtonMail::NativeIPMSign::toCpp(jniEnv, j_sign));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearPMSign(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearPMSign();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getPMEncrypt(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getPMEncrypt(::djinni::String::toCpp(jniEnv, j_group));
        return ::djinni::release(::ProtonMail::NativeIPMEncrypt::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addPMEncrypt(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_encrypt)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addPMEncrypt(::ProtonMail::NativeIPMEncrypt::toCpp(jniEnv, j_encrypt));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setPMEncrypt(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_encrypt)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setPMEncrypt(::ProtonMail::NativeIPMEncrypt::toCpp(jniEnv, j_encrypt));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearPMEncrypt(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearPMEncrypt();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getPMScheme(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getPMScheme(::djinni::String::toCpp(jniEnv, j_group));
        return ::djinni::release(::ProtonMail::NativeIPMScheme::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addPMScheme(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_scheme)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addPMScheme(::ProtonMail::NativeIPMScheme::toCpp(jniEnv, j_scheme));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setPMScheme(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_scheme)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setPMScheme(::ProtonMail::NativeIPMScheme::toCpp(jniEnv, j_scheme));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearPMScheme(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearPMScheme();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getPMMimeType(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getPMMimeType(::djinni::String::toCpp(jniEnv, j_group));
        return ::djinni::release(::ProtonMail::NativeIPMMimeType::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addPMMimeType(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_mimetype)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addPMMimeType(::ProtonMail::NativeIPMMimeType::toCpp(jniEnv, j_mimetype));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setPMMimeType(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_mimetype)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setPMMimeType(::ProtonMail::NativeIPMMimeType::toCpp(jniEnv, j_mimetype));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearPMMimeType(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearPMMimeType();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getKeys(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getKeys(::djinni::String::toCpp(jniEnv, j_group));
        return ::djinni::release(::djinni::List<::ProtonMail::NativeIKey>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addKey(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_key)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addKey(::ProtonMail::NativeIKey::toCpp(jniEnv, j_key));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setKeys(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_keys)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setKeys(::djinni::List<::ProtonMail::NativeIKey>::toCpp(jniEnv, j_keys));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearKeys(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearKeys();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getCategories(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_group)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getCategories(::djinni::String::toCpp(jniEnv, j_group));
        return ::djinni::release(::ProtonMail::NativeICategories::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addCategories(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_c)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addCategories(::ProtonMail::NativeICategories::toCpp(jniEnv, j_c));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setCategories(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_c)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setCategories(::ProtonMail::NativeICategories::toCpp(jniEnv, j_c));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearCategories(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearCategories();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getPhoto(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getPhoto();
        return ::djinni::release(::ProtonMail::NativeIPhoto::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setPhoto(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_photo)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setPhoto(::ProtonMail::NativeIPhoto::toCpp(jniEnv, j_photo));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearPhotos(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearPhotos();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getUrls(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getUrls();
        return ::djinni::release(::djinni::List<::ProtonMail::NativeIUrl>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1addUrl(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_url)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->addUrl(::ProtonMail::NativeIUrl::toCpp(jniEnv, j_url));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setUrls(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_urls)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setUrls(::djinni::List<::ProtonMail::NativeIUrl>::toCpp(jniEnv, j_urls));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearUrls(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearUrls();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getGender(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getGender();
        return ::djinni::release(::ProtonMail::NativeIGender::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setGender(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_gender)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setGender(::ProtonMail::NativeIGender::toCpp(jniEnv, j_gender));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearGender(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearGender();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1getStructuredName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        auto r = ref->getStructuredName();
        return ::djinni::release(::ProtonMail::NativeIStructuredName::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1setStructuredName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_name)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->setStructuredName(::ProtonMail::NativeIStructuredName::toCpp(jniEnv, j_name));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_native_1clearStructuredName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ProtonMail::IVCard>(nativeRef);
        ref->clearStructuredName();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_nativelib_IVCard_00024CppProxy_createInstance(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::IVCard::create_instance();
        return ::djinni::release(::ProtonMail::NativeIVCard::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace ProtonMail
