// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeIPhoto.hpp"  // my header

namespace ProtonMail {

NativeIPhoto::NativeIPhoto() : ::djinni::JniInterface<::ProtonMail::IPhoto, NativeIPhoto>("ch/protonmail/android/utils/nativelib/IPhoto$CppProxy") {}

NativeIPhoto::~NativeIPhoto() = default;


CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_IPhoto_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ProtonMail::IPhoto>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace ProtonMail
