// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeBCryptHash.hpp"  // my header
#include "jni_base_h/Marshal.hpp"

namespace ProtonMail {

NativeBCryptHash::NativeBCryptHash() : ::djinni::JniInterface<::ProtonMail::BCryptHash, NativeBCryptHash>("ch/protonmail/android/utils/nativelib/BCryptHash$CppProxy") {}

NativeBCryptHash::~NativeBCryptHash() = default;


CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_nativelib_BCryptHash_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ProtonMail::BCryptHash>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_ch_protonmail_android_utils_nativelib_BCryptHash_hashString(JNIEnv* jniEnv, jobject /*this*/, jstring j_password, jstring j_salt)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ProtonMail::BCryptHash::hash_string(::djinni::String::toCpp(jniEnv, j_password),
                                                       ::djinni::String::toCpp(jniEnv, j_salt));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace ProtonMail
