// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeAddress.hpp"  // my header
#include "NativeOpenPgpKey.hpp"
#include "jni_base_h/Marshal.hpp"

namespace ProtonMail {

NativeAddress::NativeAddress() = default;

NativeAddress::~NativeAddress() = default;

auto NativeAddress::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeAddress>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.address_id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.address_name)),
                                                           ::djinni::get(::djinni::List<::ProtonMail::NativeOpenPgpKey>::fromCpp(jniEnv, c.keys)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeAddress::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeAddress>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAddressId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAddressName)),
            ::djinni::List<::ProtonMail::NativeOpenPgpKey>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mKeys))};
}

}  // namespace ProtonMail
