// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#include "NativeOpenPgpTest.hpp"  // my header
#include "Marshal.hpp"
#include "NativeOpenPgpTest.hpp"

namespace djinni_generated {

NativeOpenPgpTest::NativeOpenPgpTest() : ::djinni::JniInterface<::OpenPgpTest, NativeOpenPgpTest>("ch/protonmail/android/utils/OpenPgpTest$CppProxy") {}

NativeOpenPgpTest::~NativeOpenPgpTest() = default;


CJNIEXPORT void JNICALL Java_ch_protonmail_android_utils_OpenPgpTest_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::OpenPgpTest>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_ch_protonmail_android_utils_OpenPgpTest_00024CppProxy_native_1decryptMessage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::OpenPgpTest>(nativeRef);
        auto r = ref->decrypt_message();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_ch_protonmail_android_utils_OpenPgpTest_createWithListener(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::OpenPgpTest::create_with_listener();
        return ::djinni::release(::djinni_generated::NativeOpenPgpTest::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
