// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include "djinni_support.hpp"
#include "open_pgp_test.hpp"

namespace djinni_generated {

class NativeOpenPgpTest final : ::djinni::JniInterface<::OpenPgpTest, NativeOpenPgpTest> {
public:
    using CppType = std::shared_ptr<::OpenPgpTest>;
    using CppOptType = std::shared_ptr<::OpenPgpTest>;
    using JniType = jobject;

    using Boxed = NativeOpenPgpTest;

    ~NativeOpenPgpTest();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeOpenPgpTest>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeOpenPgpTest>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeOpenPgpTest();
    friend ::djinni::JniClass<NativeOpenPgpTest>;
    friend ::djinni::JniInterface<::OpenPgpTest, NativeOpenPgpTest>;

};

}  // namespace djinni_generated
