// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#include "NativeOpenPgpKey.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeOpenPgpKey::NativeOpenPgpKey() = default;

NativeOpenPgpKey::~NativeOpenPgpKey() = default;

auto NativeOpenPgpKey::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeOpenPgpKey>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.public_key)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.private_key)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeOpenPgpKey::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeOpenPgpKey>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_publicKey)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_privateKey))};
}

}  // namespace djinni_generated
