// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <string>
#include <utility>
#include <vector>

namespace ProtonMail {

struct Address final {
    std::string address_id;
    /**optional */
    std::string address_name;
    std::vector<std::string> keys;

    Address(std::string address_id_,
            std::string address_name_,
            std::vector<std::string> keys_)
    : address_id(std::move(address_id_))
    , address_name(std::move(address_name_))
    , keys(std::move(keys_))
    {}
};

}  // namespace ProtonMail
