// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace ProtonMail {

class IAddress {
public:
    virtual ~IAddress() {}

    virtual std::string getStreetAddress() = 0;

    virtual std::string getExtendedAddress() = 0;

    virtual std::string getLocality() = 0;

    virtual std::string getRegion() = 0;

    virtual std::string getPostalCode() = 0;

    virtual std::string getCountry() = 0;

    virtual std::vector<std::string> getTypes() = 0;

    virtual std::string getPoBox() = 0;

    virtual std::vector<std::string> getPoBoxes() = 0;

    static std::shared_ptr<IAddress> create_instance(const std::string & type, const std::string & street, const std::string & extendstreet, const std::string & locality, const std::string & region, const std::string & zip, const std::string & country, const std::string & pobox);
};

}  // namespace ProtonMail
