// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>

namespace ProtonMail {

class IBirthday {
public:
    virtual ~IBirthday() {}

    virtual std::string getDate() = 0;

    virtual std::string getType() = 0;

    virtual std::string getText() = 0;

    static std::shared_ptr<IBirthday> create_instance(const std::string & type, const std::string & date);
};

}  // namespace ProtonMail
