// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace ProtonMail {

class ICategories {
public:
    virtual ~ICategories() {}

    virtual std::vector<std::string> getValues() = 0;

    virtual void addValue(const std::string & text) = 0;

    virtual void setValues(const std::vector<std::string> & values) = 0;

    virtual std::string getGroup() = 0;

    virtual void setGroup(const std::string & g) = 0;

    static std::shared_ptr<ICategories> create_instance(const std::string & group, const std::vector<std::string> & value);
};

}  // namespace ProtonMail
