// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace ProtonMail {

/**static create_instance(type: string, email : string, group : string) : i_email; */
class IKey {
public:
    virtual ~IKey() {}

    virtual std::string getText() = 0;

    virtual void setText(const std::string & text) = 0;

    virtual std::vector<uint8_t> getBinary() = 0;

    virtual void setBinary(const std::vector<uint8_t> & data) = 0;

    virtual std::string getGroup() = 0;

    virtual void setGroup(const std::string & g) = 0;

    virtual int32_t getPref() = 0;

    virtual void setPref(int32_t pref) = 0;
};

}  // namespace ProtonMail
