// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>
#include <vector>

namespace ProtonMail {

class INickname {
public:
    virtual ~INickname() {}

    virtual std::string getNickname() = 0;

    virtual std::string getType() = 0;

    virtual std::vector<std::string> getValues() = 0;

    static std::shared_ptr<INickname> create_instance(const std::string & type, const std::string & value);
};

}  // namespace ProtonMail
