// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>

namespace ProtonMail {

class INote {
public:
    virtual ~INote() {}

    virtual std::string getType() = 0;

    virtual std::string getNote() = 0;

    static std::shared_ptr<INote> create_instance(const std::string & type, const std::string & note);
};

}  // namespace ProtonMail
