// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

namespace ProtonMail {

class IProductId {
public:
    virtual ~IProductId() {}
};

}  // namespace ProtonMail
