// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>

namespace ProtonMail {

class IStructuredName {
public:
    virtual ~IStructuredName() {}

    virtual std::string getFamily() = 0;

    virtual std::string getGiven() = 0;

    static std::shared_ptr<IStructuredName> create_instance();
};

}  // namespace ProtonMail
