// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>

namespace ProtonMail {

class ITitle {
public:
    virtual ~ITitle() {}

    virtual std::string getTitle() = 0;

    virtual std::string getType() = 0;

    static std::shared_ptr<ITitle> create_instance(const std::string & type, const std::string & value);
};

}  // namespace ProtonMail
