// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>
#include <string>

namespace ProtonMail {

class IUid {
public:
    virtual ~IUid() {}

    virtual std::string getValue() = 0;

    static std::shared_ptr<IUid> create_instance(const std::string & uuid);
};

}  // namespace ProtonMail
