// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <memory>

namespace ProtonMail {

class IVCardVersion {
public:
    virtual ~IVCardVersion() {}

    virtual bool equals(const std::shared_ptr<IVCardVersion> & rhs) = 0;

    static std::shared_ptr<IVCardVersion> VCard2_1();

    static std::shared_ptr<IVCardVersion> VCard3_0();

    static std::shared_ptr<IVCardVersion> VCard4_0();
};

}  // namespace ProtonMail
