// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <string>
#include <utility>

namespace ProtonMail {

struct OpenPgpKey final {
    std::string key_id;
    std::string public_key;
    std::string private_key;
    std::string finger_print;

    OpenPgpKey(std::string key_id_,
               std::string public_key_,
               std::string private_key_,
               std::string finger_print_)
    : key_id(std::move(key_id_))
    , public_key(std::move(public_key_))
    , private_key(std::move(private_key_))
    , finger_print(std::move(finger_print_))
    {}
};

}  // namespace ProtonMail
