// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace ProtonMail {

struct SrpProofs;

class SrpClient {
public:
    virtual ~SrpClient() {}

    /**ExpandHash */
    static std::vector<uint8_t> expand_hash(const std::vector<uint8_t> & input);

    /**SRP */
    static SrpProofs generate_proofs(int32_t bit_length, const std::vector<uint8_t> & modulus_repr, const std::vector<uint8_t> & server_ephemeral_repr, const std::vector<uint8_t> & hashed_password_repr);

    static std::vector<uint8_t> generate_Verifier(int32_t bit_length, const std::vector<uint8_t> & modulus_repr, const std::vector<uint8_t> & hashed_password_repr);
};

}  // namespace ProtonMail
