// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_birthday.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIBirthday final : ::djinni::JniInterface<::ProtonMail::IBirthday, NativeIBirthday> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IBirthday>;
    using CppOptType = std::shared_ptr<::ProtonMail::IBirthday>;
    using JniType = jobject;

    using Boxed = NativeIBirthday;

    ~NativeIBirthday();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIBirthday>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIBirthday>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIBirthday();
    friend ::djinni::JniClass<NativeIBirthday>;
    friend ::djinni::JniInterface<::ProtonMail::IBirthday, NativeIBirthday>;

};

}  // namespace ProtonMail
