// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_telephone.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeITelephone final : ::djinni::JniInterface<::ProtonMail::ITelephone, NativeITelephone> {
public:
    using CppType = std::shared_ptr<::ProtonMail::ITelephone>;
    using CppOptType = std::shared_ptr<::ProtonMail::ITelephone>;
    using JniType = jobject;

    using Boxed = NativeITelephone;

    ~NativeITelephone();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeITelephone>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeITelephone>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeITelephone();
    friend ::djinni::JniClass<NativeITelephone>;
    friend ::djinni::JniInterface<::ProtonMail::ITelephone, NativeITelephone>;

};

}  // namespace ProtonMail
