// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_p_m_sign.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIPMSign final : ::djinni::JniInterface<::ProtonMail::IPMSign, NativeIPMSign> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IPMSign>;
    using CppOptType = std::shared_ptr<::ProtonMail::IPMSign>;
    using JniType = jobject;

    using Boxed = NativeIPMSign;

    ~NativeIPMSign();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIPMSign>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIPMSign>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIPMSign();
    friend ::djinni::JniClass<NativeIPMSign>;
    friend ::djinni::JniInterface<::ProtonMail::IPMSign, NativeIPMSign>;

};

}  // namespace ProtonMail
