// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_url.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIUrl final : ::djinni::JniInterface<::ProtonMail::IUrl, NativeIUrl> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IUrl>;
    using CppOptType = std::shared_ptr<::ProtonMail::IUrl>;
    using JniType = jobject;

    using Boxed = NativeIUrl;

    ~NativeIUrl();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIUrl>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIUrl>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIUrl();
    friend ::djinni::JniClass<NativeIUrl>;
    friend ::djinni::JniInterface<::ProtonMail::IUrl, NativeIUrl>;

};

}  // namespace ProtonMail
