// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/b_crypt_hash.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeBCryptHash final : ::djinni::JniInterface<::ProtonMail::BCryptHash, NativeBCryptHash> {
public:
    using CppType = std::shared_ptr<::ProtonMail::BCryptHash>;
    using CppOptType = std::shared_ptr<::ProtonMail::BCryptHash>;
    using JniType = jobject;

    using Boxed = NativeBCryptHash;

    ~NativeBCryptHash();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeBCryptHash>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeBCryptHash>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeBCryptHash();
    friend ::djinni::JniClass<NativeBCryptHash>;
    friend ::djinni::JniInterface<::ProtonMail::BCryptHash, NativeBCryptHash>;

};

}  // namespace ProtonMail
