// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_ezvcard.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIEzvcard final : ::djinni::JniInterface<::ProtonMail::IEzvcard, NativeIEzvcard> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IEzvcard>;
    using CppOptType = std::shared_ptr<::ProtonMail::IEzvcard>;
    using JniType = jobject;

    using Boxed = NativeIEzvcard;

    ~NativeIEzvcard();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIEzvcard>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIEzvcard>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIEzvcard();
    friend ::djinni::JniClass<NativeIEzvcard>;
    friend ::djinni::JniInterface<::ProtonMail::IEzvcard, NativeIEzvcard>;

};

}  // namespace ProtonMail
