// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_address.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIAddress final : ::djinni::JniInterface<::ProtonMail::IAddress, NativeIAddress> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IAddress>;
    using CppOptType = std::shared_ptr<::ProtonMail::IAddress>;
    using JniType = jobject;

    using Boxed = NativeIAddress;

    ~NativeIAddress();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIAddress>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIAddress>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIAddress();
    friend ::djinni::JniClass<NativeIAddress>;
    friend ::djinni::JniInterface<::ProtonMail::IAddress, NativeIAddress>;

};

}  // namespace ProtonMail
