// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_p_m_custom.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIPMCustom final : ::djinni::JniInterface<::ProtonMail::IPMCustom, NativeIPMCustom> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IPMCustom>;
    using CppOptType = std::shared_ptr<::ProtonMail::IPMCustom>;
    using JniType = jobject;

    using Boxed = NativeIPMCustom;

    ~NativeIPMCustom();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIPMCustom>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIPMCustom>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIPMCustom();
    friend ::djinni::JniClass<NativeIPMCustom>;
    friend ::djinni::JniInterface<::ProtonMail::IPMCustom, NativeIPMCustom>;

};

}  // namespace ProtonMail
