// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/lib_version.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeLibVersion final : ::djinni::JniInterface<::ProtonMail::LibVersion, NativeLibVersion> {
public:
    using CppType = std::shared_ptr<::ProtonMail::LibVersion>;
    using CppOptType = std::shared_ptr<::ProtonMail::LibVersion>;
    using JniType = jobject;

    using Boxed = NativeLibVersion;

    ~NativeLibVersion();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLibVersion>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLibVersion>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLibVersion();
    friend ::djinni::JniClass<NativeLibVersion>;
    friend ::djinni::JniInterface<::ProtonMail::LibVersion, NativeLibVersion>;

};

}  // namespace ProtonMail
