// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_organization.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIOrganization final : ::djinni::JniInterface<::ProtonMail::IOrganization, NativeIOrganization> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IOrganization>;
    using CppOptType = std::shared_ptr<::ProtonMail::IOrganization>;
    using JniType = jobject;

    using Boxed = NativeIOrganization;

    ~NativeIOrganization();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIOrganization>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIOrganization>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIOrganization();
    friend ::djinni::JniClass<NativeIOrganization>;
    friend ::djinni::JniInterface<::ProtonMail::IOrganization, NativeIOrganization>;

};

}  // namespace ProtonMail
