// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_p_m_scheme.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIPMScheme final : ::djinni::JniInterface<::ProtonMail::IPMScheme, NativeIPMScheme> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IPMScheme>;
    using CppOptType = std::shared_ptr<::ProtonMail::IPMScheme>;
    using JniType = jobject;

    using Boxed = NativeIPMScheme;

    ~NativeIPMScheme();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIPMScheme>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIPMScheme>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIPMScheme();
    friend ::djinni::JniClass<NativeIPMScheme>;
    friend ::djinni::JniInterface<::ProtonMail::IPMScheme, NativeIPMScheme>;

};

}  // namespace ProtonMail
