// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_key.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIKey final : ::djinni::JniInterface<::ProtonMail::IKey, NativeIKey> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IKey>;
    using CppOptType = std::shared_ptr<::ProtonMail::IKey>;
    using JniType = jobject;

    using Boxed = NativeIKey;

    ~NativeIKey();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIKey>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIKey>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIKey();
    friend ::djinni::JniClass<NativeIKey>;
    friend ::djinni::JniInterface<::ProtonMail::IKey, NativeIKey>;

};

}  // namespace ProtonMail
