// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_gender.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIGender final : ::djinni::JniInterface<::ProtonMail::IGender, NativeIGender> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IGender>;
    using CppOptType = std::shared_ptr<::ProtonMail::IGender>;
    using JniType = jobject;

    using Boxed = NativeIGender;

    ~NativeIGender();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIGender>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIGender>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIGender();
    friend ::djinni::JniClass<NativeIGender>;
    friend ::djinni::JniInterface<::ProtonMail::IGender, NativeIGender>;

};

}  // namespace ProtonMail
