// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_formatted_name.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIFormattedName final : ::djinni::JniInterface<::ProtonMail::IFormattedName, NativeIFormattedName> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IFormattedName>;
    using CppOptType = std::shared_ptr<::ProtonMail::IFormattedName>;
    using JniType = jobject;

    using Boxed = NativeIFormattedName;

    ~NativeIFormattedName();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIFormattedName>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIFormattedName>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIFormattedName();
    friend ::djinni::JniClass<NativeIFormattedName>;
    friend ::djinni::JniInterface<::ProtonMail::IFormattedName, NativeIFormattedName>;

};

}  // namespace ProtonMail
