// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/srp_client.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeSrpClient final : ::djinni::JniInterface<::ProtonMail::SrpClient, NativeSrpClient> {
public:
    using CppType = std::shared_ptr<::ProtonMail::SrpClient>;
    using CppOptType = std::shared_ptr<::ProtonMail::SrpClient>;
    using JniType = jobject;

    using Boxed = NativeSrpClient;

    ~NativeSrpClient();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSrpClient>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSrpClient>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSrpClient();
    friend ::djinni::JniClass<NativeSrpClient>;
    friend ::djinni::JniInterface<::ProtonMail::SrpClient, NativeSrpClient>;

};

}  // namespace ProtonMail
