// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/srp_proofs.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeSrpProofs final {
public:
    using CppType = ::ProtonMail::SrpProofs;
    using JniType = jobject;

    using Boxed = NativeSrpProofs;

    ~NativeSrpProofs();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSrpProofs();
    friend ::djinni::JniClass<NativeSrpProofs>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("ch/protonmail/android/utils/nativelib/SrpProofs") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "([B[B[B)V") };
    const jfieldID field_mClientEphemeral { ::djinni::jniGetFieldID(clazz.get(), "mClientEphemeral", "[B") };
    const jfieldID field_mClientProof { ::djinni::jniGetFieldID(clazz.get(), "mClientProof", "[B") };
    const jfieldID field_mExpectedServerProof { ::djinni::jniGetFieldID(clazz.get(), "mExpectedServerProof", "[B") };
};

}  // namespace ProtonMail
