// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_structured_name.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIStructuredName final : ::djinni::JniInterface<::ProtonMail::IStructuredName, NativeIStructuredName> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IStructuredName>;
    using CppOptType = std::shared_ptr<::ProtonMail::IStructuredName>;
    using JniType = jobject;

    using Boxed = NativeIStructuredName;

    ~NativeIStructuredName();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIStructuredName>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIStructuredName>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIStructuredName();
    friend ::djinni::JniClass<NativeIStructuredName>;
    friend ::djinni::JniInterface<::ProtonMail::IStructuredName, NativeIStructuredName>;

};

}  // namespace ProtonMail
