// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

#pragma once

#include "bridge/i_v_card.hpp"
#include "jni_base_h/djinni_support.hpp"

namespace ProtonMail {

class NativeIVCard final : ::djinni::JniInterface<::ProtonMail::IVCard, NativeIVCard> {
public:
    using CppType = std::shared_ptr<::ProtonMail::IVCard>;
    using CppOptType = std::shared_ptr<::ProtonMail::IVCard>;
    using JniType = jobject;

    using Boxed = NativeIVCard;

    ~NativeIVCard();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIVCard>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIVCard>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIVCard();
    friend ::djinni::JniClass<NativeIVCard>;
    friend ::djinni::JniInterface<::ProtonMail::IVCard, NativeIVCard>;

};

}  // namespace ProtonMail
