// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public final class EncryptPackage {


    /*package*/ final byte[] mKeyPackage;

    /*package*/ final byte[] mDataPackage;

    public EncryptPackage(
            @Nonnull byte[] keyPackage,
            @Nonnull byte[] dataPackage) {
        this.mKeyPackage = keyPackage;
        this.mDataPackage = dataPackage;
    }

    @Nonnull
    public byte[] getKeyPackage() {
        return mKeyPackage;
    }

    @Nonnull
    public byte[] getDataPackage() {
        return mDataPackage;
    }

    @Override
    public String toString() {
        return "EncryptPackage{" +
                "mKeyPackage=" + mKeyPackage +
                "," + "mDataPackage=" + mDataPackage +
        "}";
    }

}
