// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public final class EncryptSignPackage {


    /*package*/ final String mEncrypted;

    /*package*/ final String mSignature;

    public EncryptSignPackage(
            @Nonnull String encrypted,
            @Nonnull String signature) {
        this.mEncrypted = encrypted;
        this.mSignature = signature;
    }

    @Nonnull
    public String getEncrypted() {
        return mEncrypted;
    }

    @Nonnull
    public String getSignature() {
        return mSignature;
    }

    @Override
    public String toString() {
        return "EncryptSignPackage{" +
                "mEncrypted=" + mEncrypted +
                "," + "mSignature=" + mSignature +
        "}";
    }

}
