// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class ICategories {
    @Nonnull
    public abstract ArrayList<String> getValues();

    public abstract void addValue(@Nonnull String text);

    public abstract void setValues(@Nonnull ArrayList<String> values);

    @Nonnull
    public abstract String getGroup();

    public abstract void setGroup(@Nonnull String g);

    @CheckForNull
    public static native ICategories createInstance(@Nonnull String group, @Nonnull ArrayList<String> value);

    private static final class CppProxy extends ICategories
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ArrayList<String> getValues()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getValues(this.nativeRef);
        }
        private native ArrayList<String> native_getValues(long _nativeRef);

        @Override
        public void addValue(String text)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_addValue(this.nativeRef, text);
        }
        private native void native_addValue(long _nativeRef, String text);

        @Override
        public void setValues(ArrayList<String> values)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setValues(this.nativeRef, values);
        }
        private native void native_setValues(long _nativeRef, ArrayList<String> values);

        @Override
        public String getGroup()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGroup(this.nativeRef);
        }
        private native String native_getGroup(long _nativeRef);

        @Override
        public void setGroup(String g)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setGroup(this.nativeRef, g);
        }
        private native void native_setGroup(long _nativeRef, String g);
    }
}
