// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class IEzvcard {
    @CheckForNull
    public static IVCard parseFirst(@Nonnull String value)
    {
        return CppProxy.parseFirst(value);
    }

    @Nonnull
    public static ArrayList<IVCard> parseAll(@Nonnull String value)
    {
        return CppProxy.parseAll(value);
    }

    @Nonnull
    public static String write(@CheckForNull IVCard vcard)
    {
        return CppProxy.write(vcard);
    }

    @Nonnull
    public static String writeAll(@Nonnull ArrayList<IVCard> vcards)
    {
        return CppProxy.writeAll(vcards);
    }

    private static final class CppProxy extends IEzvcard
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @CheckForNull
        public static native IVCard parseFirst(@Nonnull String value);

        @Nonnull
        public static native ArrayList<IVCard> parseAll(@Nonnull String value);

        @Nonnull
        public static native String write(@CheckForNull IVCard vcard);

        @Nonnull
        public static native String writeAll(@Nonnull ArrayList<IVCard> vcards);
    }
}
