// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class IGender {
    @Nonnull
    public abstract String getGender();

    @Nonnull
    public abstract String getText();

    @CheckForNull
    public static IGender createInstance(@Nonnull String sex, @Nonnull String text)
    {
        return CppProxy.createInstance(sex,
                                       text);
    }

    private static final class CppProxy extends IGender
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public String getGender()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGender(this.nativeRef);
        }
        private native String native_getGender(long _nativeRef);

        @Override
        public String getText()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getText(this.nativeRef);
        }
        private native String native_getText(long _nativeRef);

        @CheckForNull
        public static native IGender createInstance(@Nonnull String sex, @Nonnull String text);
    }
}
