// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**static create_instance(type: string, email : string, group : string) : i_email; */
public abstract class IKey {
    @Nonnull
    public abstract String getText();

    public abstract void setText(@Nonnull String text);

    @Nonnull
    public abstract byte[] getBinary();

    public abstract void setBinary(@Nonnull byte[] data);

    @Nonnull
    public abstract String getGroup();

    public abstract void setGroup(@Nonnull String g);

    public abstract int getPref();

    public abstract void setPref(int pref);

    private static final class CppProxy extends IKey
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getText()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getText(this.nativeRef);
        }
        private native String native_getText(long _nativeRef);

        @Override
        public void setText(String text)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setText(this.nativeRef, text);
        }
        private native void native_setText(long _nativeRef, String text);

        @Override
        public byte[] getBinary()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getBinary(this.nativeRef);
        }
        private native byte[] native_getBinary(long _nativeRef);

        @Override
        public void setBinary(byte[] data)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setBinary(this.nativeRef, data);
        }
        private native void native_setBinary(long _nativeRef, byte[] data);

        @Override
        public String getGroup()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGroup(this.nativeRef);
        }
        private native String native_getGroup(long _nativeRef);

        @Override
        public void setGroup(String g)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setGroup(this.nativeRef, g);
        }
        private native void native_setGroup(long _nativeRef, String g);

        @Override
        public int getPref()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getPref(this.nativeRef);
        }
        private native int native_getPref(long _nativeRef);

        @Override
        public void setPref(int pref)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setPref(this.nativeRef, pref);
        }
        private native void native_setPref(long _nativeRef, int pref);
    }
}
