// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class ITelephone {
    @Nonnull
    public abstract ArrayList<String> getTypes();

    @Nonnull
    public abstract String getText();

    @CheckForNull
    public static native ITelephone createInstance(@Nonnull String type, @Nonnull String number);

    private static final class CppProxy extends ITelephone
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ArrayList<String> getTypes()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getTypes(this.nativeRef);
        }
        private native ArrayList<String> native_getTypes(long _nativeRef);

        @Override
        public String getText()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getText(this.nativeRef);
        }
        private native String native_getText(long _nativeRef);
    }
}
