// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class IVCardVersion {
    public abstract boolean equals(@CheckForNull IVCardVersion rhs);

    @CheckForNull
    public static IVCardVersion VCard21()
    {
        return CppProxy.VCard21();
    }

    @CheckForNull
    public static IVCardVersion VCard30()
    {
        return CppProxy.VCard30();
    }

    @CheckForNull
    public static IVCardVersion VCard40()
    {
        return CppProxy.VCard40();
    }

    private static final class CppProxy extends IVCardVersion
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public boolean equals(IVCardVersion rhs)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_equals(this.nativeRef, rhs);
        }
        private native boolean native_equals(long _nativeRef, IVCardVersion rhs);

        @CheckForNull
        public static native IVCardVersion VCard21();

        @CheckForNull
        public static native IVCardVersion VCard30();

        @CheckForNull
        public static native IVCardVersion VCard40();
    }
}
