// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import java.util.concurrent.atomic.AtomicBoolean;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class LibVersion {
    /**get lib version */
    @Nonnull
    public static String getLibVersion()
    {
        return CppProxy.getLibVersion();
    }

    /**get pgp version */
    @Nonnull
    public static String getPgpVersion()
    {
        return CppProxy.getPgpVersion();
    }

    /**get vcard version */
    @Nonnull
    public static String getVcardVersion()
    {
        return CppProxy.getVcardVersion();
    }

    private static final class CppProxy extends LibVersion
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Nonnull
        public static native String getLibVersion();

        @Nonnull
        public static native String getPgpVersion();

        @Nonnull
        public static native String getVcardVersion();
    }
}
