// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public final class OpenPgpKey {


    /*package*/ final String mPublicKey;

    /*package*/ final String mPrivateKey;

    public OpenPgpKey(
            @Nonnull String publicKey,
            @Nonnull String privateKey) {
        this.mPublicKey = publicKey;
        this.mPrivateKey = privateKey;
    }

    @Nonnull
    public String getPublicKey() {
        return mPublicKey;
    }

    @Nonnull
    public String getPrivateKey() {
        return mPrivateKey;
    }

    @Override
    public String toString() {
        return "OpenPgpKey{" +
                "mPublicKey=" + mPublicKey +
                "," + "mPrivateKey=" + mPrivateKey +
        "}";
    }

}
