// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_pgp.djinni

package ch.protonmail.android.utils.nativelib;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public final class OpenPgpKey {


    /*package*/ final String mKeyId;

    /*package*/ final String mPublicKey;

    /*package*/ final String mPrivateKey;

    /*package*/ final String mFingerPrint;

    public OpenPgpKey(
            @Nonnull String keyId,
            @Nonnull String publicKey,
            @Nonnull String privateKey,
            @Nonnull String fingerPrint) {
        this.mKeyId = keyId;
        this.mPublicKey = publicKey;
        this.mPrivateKey = privateKey;
        this.mFingerPrint = fingerPrint;
    }

    @Nonnull
    public String getKeyId() {
        return mKeyId;
    }

    @Nonnull
    public String getPublicKey() {
        return mPublicKey;
    }

    @Nonnull
    public String getPrivateKey() {
        return mPrivateKey;
    }

    @Nonnull
    public String getFingerPrint() {
        return mFingerPrint;
    }

    @Override
    public String toString() {
        return "OpenPgpKey{" +
                "mKeyId=" + mKeyId +
                "," + "mPublicKey=" + mPublicKey +
                "," + "mPrivateKey=" + mPrivateKey +
                "," + "mFingerPrint=" + mFingerPrint +
        "}";
    }

}
